# Generated by Django 4.0.4 on 2022-04-30 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0002_testimony_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='Rejected',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
