# Generated by Django 4.0.4 on 2022-05-06 23:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0003_testimony_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayerrequest',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 7, 0, 38, 58, 644724)),
        ),
        migrations.AddField(
            model_name='testimony',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 7, 0, 38, 58, 644724)),
        ),
    ]
