# Generated by Django 4.0.4 on 2022-05-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_userupdate_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userupdate',
            name='Mail_Address',
            field=models.EmailField(max_length=30, null=True),
        ),
    ]
