# Generated by Django 4.0.4 on 2022-05-06 23:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_userupdate_mail_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userupdate',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 7, 0, 38, 58, 640162)),
        ),
    ]
