# Generated by Django 4.0.4 on 2022-04-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio_Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message_Title', models.CharField(max_length=150, null=True)),
                ('Preacher_Name', models.CharField(max_length=150, null=True)),
                ('Music_file', models.FileField(upload_to='audio_messages/')),
            ],
        ),
        migrations.CreateModel(
            name='Photo_Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image_File', models.ImageField(null=True, upload_to='photo_gallery')),
                ('Image_File_2', models.ImageField(blank=True, null=True, upload_to='photo_gallery')),
                ('Image_File_3', models.ImageField(blank=True, null=True, upload_to='photo_gallery')),
                ('Image_File_4', models.ImageField(blank=True, null=True, upload_to='photo_gallery')),
                ('Image_File_5', models.ImageField(blank=True, null=True, upload_to='photo_gallery')),
                ('Image_File_6', models.ImageField(blank=True, null=True, upload_to='photo_gallery')),
                ('Image_File_7', models.ImageField(blank=True, null=True, upload_to='photo_gallery')),
                ('Image_File_8', models.ImageField(blank=True, null=True, upload_to='photo_gallery')),
                ('Image_File_9', models.ImageField(blank=True, null=True, upload_to='photo_gallery')),
                ('Image_File_10', models.ImageField(blank=True, null=True, upload_to='photo_gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Video_Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Video_Title', models.CharField(max_length=150, null=True)),
                ('Video_Id', models.CharField(max_length=50, null=True)),
                ('Video_Link', models.URLField(db_index=True, max_length=180, null=True)),
            ],
        ),
    ]
