# Generated by Django 4.0.4 on 2022-05-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo_gallery',
            name='Image_File_10',
        ),
        migrations.RemoveField(
            model_name='photo_gallery',
            name='Image_File_6',
        ),
        migrations.RemoveField(
            model_name='photo_gallery',
            name='Image_File_7',
        ),
        migrations.RemoveField(
            model_name='photo_gallery',
            name='Image_File_8',
        ),
        migrations.RemoveField(
            model_name='photo_gallery',
            name='Image_File_9',
        ),
        migrations.RemoveField(
            model_name='video_message',
            name='Video_Id',
        ),
        migrations.RemoveField(
            model_name='video_message',
            name='Video_Link',
        ),
        migrations.AddField(
            model_name='video_message',
            name='embeded_link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
