# Generated by Django 4.0.4 on 2022-05-03 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0002_remove_photo_gallery_image_file_10_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo_gallery',
            name='Image_File_2',
        ),
        migrations.RemoveField(
            model_name='photo_gallery',
            name='Image_File_3',
        ),
        migrations.RemoveField(
            model_name='photo_gallery',
            name='Image_File_4',
        ),
        migrations.RemoveField(
            model_name='photo_gallery',
            name='Image_File_5',
        ),
    ]
