# Generated by Django 4.0.4 on 2022-05-06 23:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0004_audio_message_created_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio_message',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 7, 0, 40, 13, 592820)),
        ),
        migrations.AlterField(
            model_name='photo_gallery',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 7, 0, 40, 13, 593804)),
        ),
        migrations.AlterField(
            model_name='video_message',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 7, 0, 40, 13, 593804)),
        ),
    ]
