# Generated by Django 4.0.4 on 2022-05-06 23:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control', '0002_program_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 7, 0, 40, 13, 591825)),
        ),
    ]
